# Generated by Django 5.2.6 on 2026-06-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
