# Generated by Django 5.2.6 on 2026-07-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_question_choice_quizsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
