# Generated by Django 5.2.6 on 2026-07-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_free_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
