# Generated by Django 5.2.6 on 2026-07-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courseprogress_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
