# Generated by Django 6.0 on 2026-01-19 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursepayment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='transaction_ref',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coursepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coursepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Echoué')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='coursepayment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='coursepayment',
            name='transaction_id',
        ),
    ]
