# Generated by Django 6.0 on 2026-03-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_alter_coursepayment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/videos/'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='courses/docs/'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
