# Generated by Django 5.2.6 on 2026-07-11 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0008_remove_course_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.IntegerField(help_text="Numéro de l'exercice au sein du cours (ex: 1, 2, 3)")),
                ('title', models.CharField(max_length=200, verbose_name="Intitulé de l'exercice")),
                ('desc', models.TextField(verbose_name='Description / Consigne')),
                ('difficulty', models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Avancé', 'Avancé')], default='Débutant', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.course', verbose_name='Cours associé')),
            ],
            options={
                'ordering': ['exercise_id'],
                'unique_together': {('course', 'exercise_id')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Non lancé'), ('in_progress', 'En cours'), ('pending', 'En attente de validation'), ('validated', "Validé par l'Admin")], default='not_started', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('admin_feedback', models.TextField(blank=True, null=True, verbose_name="Commentaire de l'enseignant")),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exercice.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'exercise')},
            },
        ),
    ]
